baseURL = "https://www.lolrmm.com/"
title = "lolrmm.com"
enableRobotsTXT = true
theme = ["compose"]
enableGitInfo = true
googleAnalytics = "G-9F510YT8DQ"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[mediaTypes]
  [mediaTypes."text/csv"]
    suffixes = ["csv"]

[outputFormats.CSV]
  mediaType = "text/csv"
  isPlainText = true

[params]
  [params.csv]
    delimiter = ","