name: Deploy site

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.12
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.12
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python -
    - name: Install dependencies with Poetry
      run: poetry install
    - name: Generate MDX
      run: poetry run python bin/site.py -v
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
    - name: Pull Vercel Environment Information
      run: vercel --cwd=website pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
    - name: Build Project Artifacts
      run: vercel --cwd=website build --prod --token=${{ secrets.VERCEL_TOKEN }}
    - name: Deploy Project Artifacts to Vercel
      run: vercel --cwd=website deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
